name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g marked@latest

      - name: Convert Markdown to HTML
        run: |
          mkdir -p _site/post
          for md in post/*.md; do
            filename=$(basename "$md" .md)
            echo "Converting $md to $filename.html"
            marked "$md" > "_site/post/$filename.html"
            sed -i "s|{{title}}|$(grep '^title:' "$md" | cut -d':' -f2- | xargs)|g" "_site/post/$filename.html"
          done

      - name: Copy static files
        run: |
          cp index.html _site/
          cp styles.css _site/
          cp script.js _site/
          cp -r images _site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site