name: Generate Manifest
on: [push]

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install beautifulsoup4  # Tambahkan ini
      
      - name: Generate Manifest
        run: |
          echo "Generating manifest.json..."
          python3 <<EOF
          import os
          import json
          from bs4 import BeautifulSoup

          manifest = []
          post_dir = 'post'
          
          for filename in os.listdir(post_dir):
              if filename.endswith('.html'):
                  with open(os.path.join(post_dir, filename), 'r') as f:
                      soup = BeautifulSoup(f.read(), 'html.parser')
                      script = soup.find('script', {'type': 'application/json', 'id': 'metadata'})
                      if script:
                          try:
                              data = json.loads(script.string)
                              data['file'] = filename
                              manifest.append(data)
                          except json.JSONDecodeError as e:
                              print(f"Error parsing JSON in {filename}: {str(e)}")
          
          with open(os.path.join(post_dir, 'manifest.json'), 'w') as f:
              json.dump(manifest, f, indent=2, ensure_ascii=False)
          EOF

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add post/manifest.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update manifest"
          git push